name: Build and deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm i

      - name: Build
        env:
          PUBLIC_URL: 'https://ken-all.github.io/kenall-js-demo'
          VITE_BASE_URL: '/kenall-js-demo'
          VITE_KENALL_API_KEY: ${{ secrets.KENALL_API_KEY }}
        run: |
          set -xe
          npm run build
          src="dist/index.html"
          for f in src/pages/*.tsx; do
            dest="dist/$(echo "$f" | sed -e 's#src/pages/\([^/]*\)\.tsx#\1.html#')"
            if [ "${dest}" != "${src}" ]; then
              cp "${src}" "${dest}"
            fi
          done

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
